### ISSUE TITLE
how to implement this website?

### ISSUE THREAD

**Issue by FutureWithoutEnding** [amberyic/blog#2]
Your website is very good. I like it.
I want to have a website like this, how to do it.

**Comment by amberyic** [comment]
thank you for recognition, I build my blog based on hexo with fluid theme, the link below may help you:
- https://hexo.io/zh-cn/
- https://fluid-dev.github.io/hexo-fluid-docs/

**Comment by FutureWithoutEnding** [comment]
Thanks.
